### ISSUE TITLE
Escrever estilo da barra para impressão

### ISSUE THREAD

**Issue by valessiobrito** [govbr/barra.govbr#8]
Atualmente a Barra não possui estilo para impressão, sugiro criar um estilo minimo para barra ser melhor visualizada quando impresso, exemplo a bandeira que não renderiza. Ex. cód.:
```css
@media print {
    blih {
          color: #000;
    }
    /* etc */
}
```
![barrabr](https://cloud.githubusercontent.com/assets/310049/7312050/fe5a38fa-ea1b-11e4-9196-edb2dc0a1448.png)
